// Generated by gencpp from file nox_msgs/Boundary.msg
// DO NOT EDIT!


#ifndef NOX_MSGS_MESSAGE_BOUNDARY_H
#define NOX_MSGS_MESSAGE_BOUNDARY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nox_msgs/Bound.h>
#include <nox_msgs/Function.h>

namespace nox_msgs
{
template <class ContainerAllocator>
struct Boundary_
{
  typedef Boundary_<ContainerAllocator> Type;

  Boundary_()
    : id(0)
    , s()
    , func()
    , passable(false)  {
    }
  Boundary_(const ContainerAllocator& _alloc)
    : id(0)
    , s(_alloc)
    , func(_alloc)
    , passable(false)  {
  (void)_alloc;
    }



   typedef uint64_t _id_type;
  _id_type id;

   typedef  ::nox_msgs::Bound_<ContainerAllocator>  _s_type;
  _s_type s;

   typedef  ::nox_msgs::Function_<ContainerAllocator>  _func_type;
  _func_type func;

   typedef uint8_t _passable_type;
  _passable_type passable;





  typedef boost::shared_ptr< ::nox_msgs::Boundary_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nox_msgs::Boundary_<ContainerAllocator> const> ConstPtr;

}; // struct Boundary_

typedef ::nox_msgs::Boundary_<std::allocator<void> > Boundary;

typedef boost::shared_ptr< ::nox_msgs::Boundary > BoundaryPtr;
typedef boost::shared_ptr< ::nox_msgs::Boundary const> BoundaryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nox_msgs::Boundary_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nox_msgs::Boundary_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nox_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nox_msgs': ['/media/yarten/DATA/Project/ROS/NOX_Project/nox/src/nox_msgs/msg'], 'nav_msgs': ['/opt/ros/melodic/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nox_msgs::Boundary_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nox_msgs::Boundary_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nox_msgs::Boundary_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nox_msgs::Boundary_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nox_msgs::Boundary_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nox_msgs::Boundary_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nox_msgs::Boundary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3908a017a5fe55cb0e00fa19d085f7cb";
  }

  static const char* value(const ::nox_msgs::Boundary_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3908a017a5fe55cbULL;
  static const uint64_t static_value2 = 0x0e00fa19d085f7cbULL;
};

template<class ContainerAllocator>
struct DataType< ::nox_msgs::Boundary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nox_msgs/Boundary";
  }

  static const char* value(const ::nox_msgs::Boundary_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nox_msgs::Boundary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Description of a boundary along a guide line\n"
"\n"
"uint64    id\n"
"Bound     s          # 边界在引导线上附着的位置\n"
"Function  func       # 描述边界的数学函数\n"
"bool      passable   # 可通行的\n"
"================================================================================\n"
"MSG: nox_msgs/Bound\n"
"float64 lower # lower bound\n"
"float64 upper # upper bound\n"
"================================================================================\n"
"MSG: nox_msgs/Function\n"
"# Description of a math function\n"
"\n"
"float64[] coeff  # 函数系数\n"
"Bound   x        # 定义域\n"
"\n"
"# -----------------------------------\n"
"uint32  type     # 函数类型（决定了系数的意义）\n"
"\n"
"uint32 Unknown    = 0\n"
"uint32 Polynomial = 1\n"
;
  }

  static const char* value(const ::nox_msgs::Boundary_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nox_msgs::Boundary_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.s);
      stream.next(m.func);
      stream.next(m.passable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Boundary_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nox_msgs::Boundary_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nox_msgs::Boundary_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.id);
    s << indent << "s: ";
    s << std::endl;
    Printer< ::nox_msgs::Bound_<ContainerAllocator> >::stream(s, indent + "  ", v.s);
    s << indent << "func: ";
    s << std::endl;
    Printer< ::nox_msgs::Function_<ContainerAllocator> >::stream(s, indent + "  ", v.func);
    s << indent << "passable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.passable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOX_MSGS_MESSAGE_BOUNDARY_H
