// Generated by gencpp from file nox_msgs/GetScene.msg
// DO NOT EDIT!


#ifndef NOX_MSGS_MESSAGE_GETSCENE_H
#define NOX_MSGS_MESSAGE_GETSCENE_H

#include <ros/service_traits.h>


#include <nox_msgs/GetSceneRequest.h>
#include <nox_msgs/GetSceneResponse.h>


namespace nox_msgs
{

struct GetScene
{

typedef GetSceneRequest Request;
typedef GetSceneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetScene
} // namespace nox_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nox_msgs::GetScene > {
  static const char* value()
  {
    return "aea46206a9040866717eaeb2d525089b";
  }

  static const char* value(const ::nox_msgs::GetScene&) { return value(); }
};

template<>
struct DataType< ::nox_msgs::GetScene > {
  static const char* value()
  {
    return "nox_msgs/GetScene";
  }

  static const char* value(const ::nox_msgs::GetScene&) { return value(); }
};


// service_traits::MD5Sum< ::nox_msgs::GetSceneRequest> should match 
// service_traits::MD5Sum< ::nox_msgs::GetScene > 
template<>
struct MD5Sum< ::nox_msgs::GetSceneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nox_msgs::GetScene >::value();
  }
  static const char* value(const ::nox_msgs::GetSceneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nox_msgs::GetSceneRequest> should match 
// service_traits::DataType< ::nox_msgs::GetScene > 
template<>
struct DataType< ::nox_msgs::GetSceneRequest>
{
  static const char* value()
  {
    return DataType< ::nox_msgs::GetScene >::value();
  }
  static const char* value(const ::nox_msgs::GetSceneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nox_msgs::GetSceneResponse> should match 
// service_traits::MD5Sum< ::nox_msgs::GetScene > 
template<>
struct MD5Sum< ::nox_msgs::GetSceneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nox_msgs::GetScene >::value();
  }
  static const char* value(const ::nox_msgs::GetSceneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nox_msgs::GetSceneResponse> should match 
// service_traits::DataType< ::nox_msgs::GetScene > 
template<>
struct DataType< ::nox_msgs::GetSceneResponse>
{
  static const char* value()
  {
    return DataType< ::nox_msgs::GetScene >::value();
  }
  static const char* value(const ::nox_msgs::GetSceneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NOX_MSGS_MESSAGE_GETSCENE_H
