// Generated by gencpp from file nox_msgs/Road.msg
// DO NOT EDIT!


#ifndef NOX_MSGS_MESSAGE_ROAD_H
#define NOX_MSGS_MESSAGE_ROAD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nox_msgs/RoadBlock.h>

namespace nox_msgs
{
template <class ContainerAllocator>
struct Road_
{
  typedef Road_<ContainerAllocator> Type;

  Road_()
    : header()
    , blocks()
    , status(0)  {
    }
  Road_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , blocks(_alloc)
    , status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::nox_msgs::RoadBlock_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nox_msgs::RoadBlock_<ContainerAllocator> >::other >  _blocks_type;
  _blocks_type blocks;

   typedef int32_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::nox_msgs::Road_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nox_msgs::Road_<ContainerAllocator> const> ConstPtr;

}; // struct Road_

typedef ::nox_msgs::Road_<std::allocator<void> > Road;

typedef boost::shared_ptr< ::nox_msgs::Road > RoadPtr;
typedef boost::shared_ptr< ::nox_msgs::Road const> RoadConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nox_msgs::Road_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nox_msgs::Road_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nox_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nox_msgs': ['/media/yarten/DATA/Project/ROS/NOX_Project/nox/src/nox_msgs/msg'], 'nav_msgs': ['/opt/ros/melodic/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nox_msgs::Road_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nox_msgs::Road_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nox_msgs::Road_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nox_msgs::Road_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nox_msgs::Road_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nox_msgs::Road_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nox_msgs::Road_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8db52b0652f86b380c1af20d90bd962c";
  }

  static const char* value(const ::nox_msgs::Road_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8db52b0652f86b38ULL;
  static const uint64_t static_value2 = 0x0c1af20d90bd962cULL;
};

template<class ContainerAllocator>
struct DataType< ::nox_msgs::Road_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nox_msgs/Road";
  }

  static const char* value(const ::nox_msgs::Road_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nox_msgs::Road_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"RoadBlock[] blocks\n"
"\n"
"int32 status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nox_msgs/RoadBlock\n"
"RoadPoint[] points # 可以选择的道路点\n"
"int32 target_index # 推荐的道路点\n"
"float64 minSpeed\n"
"float64 maxSpeed\n"
"\n"
"================================================================================\n"
"MSG: nox_msgs/RoadPoint\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::nox_msgs::Road_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nox_msgs::Road_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.blocks);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Road_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nox_msgs::Road_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nox_msgs::Road_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "blocks[]" << std::endl;
    for (size_t i = 0; i < v.blocks.size(); ++i)
    {
      s << indent << "  blocks[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nox_msgs::RoadBlock_<ContainerAllocator> >::stream(s, indent + "    ", v.blocks[i]);
    }
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOX_MSGS_MESSAGE_ROAD_H
