// Generated by gencpp from file nox_msgs/StopLine.msg
// DO NOT EDIT!


#ifndef NOX_MSGS_MESSAGE_STOPLINE_H
#define NOX_MSGS_MESSAGE_STOPLINE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nox_msgs
{
template <class ContainerAllocator>
struct StopLine_
{
  typedef StopLine_<ContainerAllocator> Type;

  StopLine_()
    : id(0)
    , s(0.0)  {
    }
  StopLine_(const ContainerAllocator& _alloc)
    : id(0)
    , s(0.0)  {
  (void)_alloc;
    }



   typedef uint64_t _id_type;
  _id_type id;

   typedef double _s_type;
  _s_type s;





  typedef boost::shared_ptr< ::nox_msgs::StopLine_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nox_msgs::StopLine_<ContainerAllocator> const> ConstPtr;

}; // struct StopLine_

typedef ::nox_msgs::StopLine_<std::allocator<void> > StopLine;

typedef boost::shared_ptr< ::nox_msgs::StopLine > StopLinePtr;
typedef boost::shared_ptr< ::nox_msgs::StopLine const> StopLineConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nox_msgs::StopLine_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nox_msgs::StopLine_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nox_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nox_msgs': ['/media/yarten/DATA/Project/ROS/NOX_Project/nox/src/nox_msgs/msg'], 'nav_msgs': ['/opt/ros/melodic/share/nav_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nox_msgs::StopLine_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nox_msgs::StopLine_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nox_msgs::StopLine_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nox_msgs::StopLine_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nox_msgs::StopLine_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nox_msgs::StopLine_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nox_msgs::StopLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "42ffae2570c8861ea1bc615400b01c22";
  }

  static const char* value(const ::nox_msgs::StopLine_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x42ffae2570c8861eULL;
  static const uint64_t static_value2 = 0xa1bc615400b01c22ULL;
};

template<class ContainerAllocator>
struct DataType< ::nox_msgs::StopLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nox_msgs/StopLine";
  }

  static const char* value(const ::nox_msgs::StopLine_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nox_msgs::StopLine_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Description of the stop line on the map\n"
"\n"
"uint64  id\n"
"float64 s\n"
;
  }

  static const char* value(const ::nox_msgs::StopLine_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nox_msgs::StopLine_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.s);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopLine_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nox_msgs::StopLine_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nox_msgs::StopLine_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.id);
    s << indent << "s: ";
    Printer<double>::stream(s, indent + "  ", v.s);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NOX_MSGS_MESSAGE_STOPLINE_H
